# Generated by Django 5.0.6 on 2024-05-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_alter_profile_image_chatmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage", old_name="message", new_name="text_message",
        ),
    ]
